# https://numtide.github.io/devshell
imports = ["language/c", "language/go", "language/rust"]

[language.c]
compiler = "unstable.clang"
includes = []

[[commands]]
package = "unstable.treefmt"

[devshell]
packages = ["pkgs.nixpkgs-fmt", "pkgs.taplo", "pkgs.black"]
