# https://github.com/numtide/treefmt

[global]
excludes = ["*.sops.*"]

[formatter.nixpkgs-fmt]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.taplo]
command = "taplo"
includes = ["*.toml"]
options = ["format"]

[formatter.black]
command = "black"
includes = ["*.py", "*.pyi"]
