# https://github.com/numtide/treefmt

[global]
excludes = ["*.sops.*"]

[formatter.mdformat]
command = "mdformat"
includes = ["*.md"]

[formatter.nixpkgs-fmt]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.taplo]
command = "taplo"
includes = ["*.toml"]
options = ["format"]

[formatter.black]
command = "black"
includes = ["*.py", "*.pyi"]

[formatter.sqlfluff]
command = "sqlfluff"
includes = ["*.sql"]
options = ["format", "--disable-progress-bar", "--processes", "0"]

[formatter.gofmt]
command = "gofmt"
excludes = ["vendor/*"]
includes = ["*.go"]
options = ["-w"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]
